name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        run: rustup default stable
      
      - name: Build
        run: cmd /c build.cmd
      
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.exe
            *.sha256.txt
          draft: true
          generate_release_notes: true
